### ISSUE TITLE
extended-json

### ISSUE THREAD

**Issue by alexbyk** [mongodb/js-bson#198]
Could you please include extended-json to npm release and document it?

**Comment by alexbyk** [comment]
Also why toJSON returns string/num instead of documented [here](https://docs.mongodb.com/v3.2/reference/mongodb-extended-json/) objects? That produces unexpected results

**Comment by christkv** [comment]
You should ask at the authors of the extended-json module about that. The bson parser does not support that format and probably won't any time soon due to backward compatibility issues. However at some point in the next couple of months I plan to release a full extended json implementation module that will support the currently being worked on full specification.
