### ISSUE TITLE
Import bson.js to WebWprker: error "Cannot find module "buffer""

### ISSUE THREAD

**Issue by annmirosh** [mongodb/js-bson#215]
Hi, guys!

Is it possible to use bson.js in WebWorker?

I'm using importScripts to import bson.js (from the browser_build/bson.js) to WebWorker, but getting error: Uncaught Error: Cannot find module "buffer" @[module: binary package: bson]. Here is a plunker example: https://plnkr.co/edit/8AXGg7jiBu32eBa7qjB8?p=info

Can you please suggest how to use it to serialize and deserialize data in the WebWorker?

**Comment by mbroadst** [comment]
@annmirosh hmm which build of `bson.js` are you using?  The problem in the code you linked to is this problematic line:
```
    if(typeof window === 'undefined') {
        var Buffer = require('buffer').Buffer; // TODO just use global Buffer
    }
```

It's attempting to discover that we're running not in the browser, and therefore assuming we're in a node environment.  This of course will fail in your case because the worker is operating in an environment where there is no window, but it's definitely not in node!  What's confusing to me is that your copy of the browser built version of the module is not what's on the github repo right now, so that's making it a little difficult to dive deeper.

**Comment by mbroadst** [comment]
This should be fixed with one of the current browser builds. Please reopen if you have more information
