### ISSUE TITLE
need examples

### ISSUE THREAD

**Issue by acthp** [mongodb/js-bson#308]
The API is extremely unclear. Are there better docs anywhere? Or examples? The unit tests aren't very useful as examples. 

E.g. how do you use the binary type? Looks like with ```new Binary(array)```, but then what? This, for example, doesn't work:

```
bson.serialize({foo: new bson.Binary(new Uint8Array(10))})
```
and throws
```
  data.copy(buffer, index, 0, value.position);
       ^

TypeError: data.copy is not a function
```

**Comment by justingrant** [comment]
@acthp - Not sure about examples but I've been spending a lot of time using this library recently and I may able to help you with this particular error. The code that's failing is in the serializer-- search through `serializer.js` to find the culprit line. 

I suspect the problem you're running into is one of the following possible root causes:
* The 4.0.1 serializer may not be compatible with native [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array). If this is the case, you should use [Buffer](https://nodejs.org/api/buffer.html) instead-- this library long predates `Uint8Array`. If you're running in the browser then you'll have to use a polyfill, e.g. https://github.com/feross/buffer. 
* The 4.0.1 serializer might work for Uint8Array in Node environments, but not in browser environments. If this is the case, you'll want to try a Buffer polyfill. 
* The 4.0.1 serializer may not work at all for Binary data, even when using the Buffer type in Node environments. This is probably unlikely since presumably it'd trigger unit test failures, but it's possible.
* You may be running into a problem in the older version of this library that's included in `mongodb` and `mongodb-core` packages. Unfortunately the older library is not perfectly compatible with v4 of the library. You might want to try your code in both the old version (e.g. `import {BSON} from MongoDB`) and new version (e.g. `import BSON from 'bson'`). If it only breaks in one of them, that's useful info. 

If you find the root cause, I'd encourage you to file a PR. I filed a bunch of PRs this week and I have found the maintainers to be friendly and to be quick to merge bug fixes.

Please reply with what you find-- this problem definitely seems like something worth fixing.

**Comment by daprahamian** [comment]
Hi @acthp,

@justingrant's analysis is correct. Specifically, the 4.x `bson` does not officially support `Uint8Array`. We do have some catches for it in various places, but overall the library will not work without either the Node `Buffer` class or a `Buffer` polyfill being available. You should be able to do:

```js
bson.serialize({foo: new bson.Binary(Buffer.alloc(10))})
```

As for documentation and examples, one of our upcoming goals is to make all of our documentation easier to access, and in a more centralized location. If you'd like to request specific examples, you can file a ticket on our JIRA (instructions [here](https://github.com/mongodb/js-bson#bugs--feature-requests))
