### ISSUE TITLE
How to convert Timestamp type to milliseconds

### ISSUE THREAD

**Issue by BainDragneel** [mongodb/js-bson#337]
I want to know if there is a way to convert the value of the mongodb Timestamp type to milliseconds or provide a timestamp to convert to a timestamp.

**Comment by nbbeeken** [comment]
The timestamp type is for internal use in mongodb, I think if you want to track datetimes you should Javascript Date which will serialize to a UTC Datetime. I don't believe you can convert a Timestamp to milliseconds since it represents a time in seconds combined with a counter based on operations performed in the DB.

You can find more assistance on our developer forums:
https://developer.mongodb.com/community/forums/
