### ISSUE TITLE
ObjectId.isValid('123456789012') === true

### ISSUE THREAD

**Issue by j** [mongodb/js-bson#365]
`isValid` is checking if the string is length 12 or 24.  It should check if byte length is 12 AND matches the regex.

Can probably just remove the `id.length === 12` check or use `Buffer.byteLength(id, 'hex')`?

**Comment by borsucok** [comment]
I solved this this way:

```javascript
function objectIdIsValid(oid) {
  if (oid instanceof ObjectID) {
    return true;
  }
  if (ObjectID.isValid(oid)) {
    const oido = ObjectID(oid);
    if (oido.toHexString() === oid) {
      return true;
    }
  }
  return false;
}
```

**Comment by j** [comment]
Yes, that's essentially what I'm doing, but the internal isValid method needs to be fixed.

**Comment by nbbeeken** [comment]
Hello, thanks for submitting an issue! This behavior is expected since the strings passed to the constructor and this isValid method that are 12 units in length are interpreted as a binary sequence.

For example these two ObjectIds are equal:
```js
new ObjectId('\x31\x32\x33\x34\x35\x36\x37\x38\x39\x30\x31\x32')
new ObjectId('123456789012')
```
Another example of a random ObjectId makes this more clear: 
```js
// A random oid I just made:
// ObjectId('5fd0f17e8e840df1c9687f37')
// this can be constructed from the string:
new ObjectId('_Ðñ~\x8E\x84\rñÉh\x7F7') // this could just as well be all `\xDD` escaped hex bytes
```

I'll close this for now, please feel free to reopen if there's further issues.
