### ISSUE TITLE
serializer has bad parameter structure

### ISSUE THREAD

**Issue by Uzlopak** [mongodb/js-bson#385]
Imho the serializer method heads are bad. The last parameter is isArray but actually all it does is depending if it is true or false it will set the corresponding encoding to ascii or utf8.
``` const numberOfWrittenBytes = !isArray
    ? buffer.write(key, index, 'utf8')
    : buffer.write(key, index, 'ascii');
```

So actually the last parameter is about encoding and not if the input is an array or not. So probably we should rename it to encoding and insert directly if it should be using utf8 or ascii. This should remove a lot of if checks also. 

Also strange is this function call:

https://github.com/mongodb/js-bson/blob/4c6f2e4f7f39e75274dd12e67d34befb4fd6ea28/lib/parser/serializer.js#L853

Why is serializeFunctions passed to serializeFunction as parameter isArray?

**Comment by Uzlopak** [comment]
Potentially removing all these redundant if checks would reduce overhead and increase performance. Also by setting all parameters of the serializer methods the V8 should optimize it better.

**Comment by agolin95** [comment]
https://jira.mongodb.org/browse/NODE-3033

**Comment by zbjornson** [comment]
I'm almost certain that those lines were intended to be an optimization: when encoding an array, the keys are known to be ASCII and theoretically can use faster serialization. However, V8 knows if strings only contain one-byte characters and [automatically uses one-byte serialization](https://github.com/nodejs/node/blob/2b080cb23fac2320c84d79c76603a8a7f9b9a7bc/deps/v8/src/api/api.cc#L5482-L5488). I can't detect a difference between `buffer.write(key_that_is_ascii, index, "utf8"/*OR*/"ascii")` in small benchmarks.

This, however, is roughly 3x as fast, in large part because avoids a C++ boundary:

```js
function write_ascii_int(buf, offset, val) {
	const s = val.toString();
	for (let i = 0; i < s.length; i++)
		buf[offset + i] = s.charCodeAt(i);
}
```

**Comment by bajanam** [comment]
This issue is being tracked in Jira, please continue all conversations in the corresponding Jira ticket.  Thanks!
